spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/mydb
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: 123

# spring:
#     data:
#         mongodb:
#             uri: mongodb://localhost:27017/mydbname


